# Generated by Django 5.1.7 on 2025-04-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
