# Generated by Django 5.1.7 on 2025-04-27 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_feedback_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_email',
        ),
    ]
